name: Example_Alex
description: outputs "Example_Alex" and the input "alex-input" from a ruby file
inputs:
  alex-input:
    description: alex input
    required: false
    default: 'no input given for alex-input'

runs:
  using: composite
  steps:
    - run: ruby $GITHUB_ACTION_PATH/main.rb
      shell: bash
      env:
        ALEX_INPUT: ${{ inputs.alex-input }} aaa${{ github.repository }}aaa
