name: Example_Alex in this proj

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run Example_Alex action
        uses: ./example_alex
